import React,{useRef} from 'react';
import {ChevronLeft,ChevronRight,Check,Pencil} from 'lucide-react';
import {labels,artUrl} from './art';
const tabs=[['animals','🦁','동물','#ffe19c'],['objects','🚀','탈것','#b4e1ff'],['fairies','🧚','요정','#e3c5ff'],['princesses','👑','공주','#ffbfd7'],['basic','⭐','기본','#c1edcc']];
export function DrawingGallery({category,setCategory,page,setPage,items,selected,onSelect}){
 const gesture=useRef(null),blockClick=useRef(false);const pages=Math.ceil(items.length/8);
 function end(e){const g=gesture.current;gesture.current=null;if(!g||g.id!==e.pointerId)return;if(g.drag){e.preventDefault();const dx=e.clientX-g.x;if(Math.abs(dx)>55)setPage(p=>Math.max(0,Math.min(pages-1,p+(dx<0?1:-1))));}}
 return <><div className="category-tabs" aria-label="도안 종류">{tabs.map(([id,emoji,name,tint])=><button key={id} aria-label={name} aria-pressed={category===id} style={{'--tab-color':tint}} onClick={()=>{setCategory(id);setPage(0);}}><span aria-hidden="true">{emoji}</span><small>{name}</small></button>)}</div>
 <div className="drawing-list" onPointerDown={e=>{if(!e.isPrimary||e.button!==0)return;blockClick.current=false;gesture.current={id:e.pointerId,x:e.clientX,y:e.clientY,drag:false};}} onPointerMove={e=>{const g=gesture.current;if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)){g.drag=true;blockClick.current=true;e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();}}} onPointerUp={end} onPointerCancel={()=>{gesture.current=null;blockClick.current=true;}} onLostPointerCapture={()=>{gesture.current=null;}} onClickCapture={e=>{if(blockClick.current&&e.detail!==0){e.preventDefault();e.stopPropagation();}}}>
 {items.slice(page*8,page*8+8).map((id,i)=><button key={id} className={'drawing-card '+(selected===id?'selected':'')} style={{'--card-color':['#fff4cf','#e5f4ff','#ffe9f0','#e9f7e9'][i%4]}} onClick={()=>onSelect(id)} aria-label={labels[id]+' 밑그림 선택'} aria-pressed={selected===id}>{id==='blank'?<Pencil className="blank-art-icon" size={68} aria-hidden="true"/>:<img src={artUrl(id)} alt="" draggable="false"/>}{selected===id&&<span className="selected-art" aria-hidden="true"><Check size={22}/></span>}</button>)}
 </div><div className="picker-pages visual-pages"><button disabled={page===0} onClick={()=>setPage(page-1)} aria-label="이전 도안"><ChevronLeft size={32}/></button><div className="page-dots">{Array.from({length:pages},(_,i)=><button key={i} aria-label={`도안 ${i+1}페이지`} aria-current={page===i?'page':undefined} onClick={()=>setPage(i)}><span/></button>)}</div><button disabled={page===pages-1} onClick={()=>setPage(page+1)} aria-label="다음 도안"><ChevronRight size={32}/></button></div></>;
}
