import React,{useRef} from 'react';
import {ChevronLeft,ChevronRight} from 'lucide-react';
import {labels,artUrl} from './art';
const tabs=[['animals','🦁','동물','#ffcc65'],['objects','🚀','탈것','#8ed4ff'],['fairies','🧚','요정','#cf9dff'],['princesses','👑','공주','#ff9ec4'],['roles','🧑‍🚒','직업과 역할','#ffb788'],['basic',null,'자유 그리기','#83dfb3']];
export function Sketchbook(){return <svg className="sketchbook-icon" viewBox="0 0 120 100" aria-hidden="true"><rect x="15" y="12" width="77" height="79" rx="12" fill="#d6c5f0"/><rect x="12" y="7" width="77" height="79" rx="10" fill="white" stroke="#aa8ece" strokeWidth="3"/>{[22,40,58,76].map(y=><path key={y} d={`M8 ${y}h12`} stroke="#9272b8" strokeWidth="5" strokeLinecap="round"/>)}{[['#ff777f',74,27],['#ffcd57',86,34],['#51cbb7',98,41]].map(([color,x,y])=><g key={color} transform={`translate(${x} ${y}) rotate(26)`}><rect width="11" height="43" rx="3" fill={color}/><path d="M0 43 L5.5 55 L11 43" fill={color}/><path d="M1 10H10M1 33H10" stroke="white" strokeWidth="3"/></g>)}</svg>}
export function DrawingGallery({category,setCategory,page,setPage,items,selected,onSelect}){
 const gesture=useRef(null),blockClick=useRef(false);const pages=Math.ceil(items.length/8);
 function end(e){const g=gesture.current;gesture.current=null;if(!g||g.id!==e.pointerId)return;e.currentTarget.style.transform='';if(g.drag){e.preventDefault();const dx=e.clientX-g.x,elapsed=performance.now()-g.time;if(Math.abs(dx)>55||(Math.abs(dx)>30&&elapsed<250))setPage(p=>Math.max(0,Math.min(pages-1,p+(dx<0?1:-1))));}}
 return <><div className="category-tabs" aria-label="도안 종류">{tabs.map(([id,emoji,name,tint])=><button key={id} aria-label={name} aria-pressed={category===id} style={{'--tab-color':tint}} onClick={()=>{setCategory(id);setPage(0);}}><span aria-hidden="true">{emoji||<Sketchbook/>}</span></button>)}</div>
 <div key={category+page} className="drawing-list" onPointerDown={e=>{if(!e.isPrimary||e.button!==0)return;blockClick.current=false;gesture.current={id:e.pointerId,x:e.clientX,y:e.clientY,time:performance.now(),drag:false};}} onPointerMove={e=>{const g=gesture.current;if(!g||g.id!==e.pointerId)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)){g.drag=true;blockClick.current=true;e.currentTarget.style.transform=`translateX(${Math.max(-32,Math.min(32,dx*.2))}px)`;e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();}}} onPointerUp={end} onPointerCancel={e=>{gesture.current=null;blockClick.current=true;e.currentTarget.style.transform='';}} onLostPointerCapture={e=>{gesture.current=null;e.currentTarget.style.transform='';}} onClickCapture={e=>{if(blockClick.current&&e.detail!==0){e.preventDefault();e.stopPropagation();}}}>
 {items.slice(page*8,page*8+8).map((id,i)=><button key={id} className={'drawing-card '+(selected===id?'selected':'')} style={{'--card-color':['#fff4cf','#e5f4ff','#ffe9f0','#e9f7e9'][i%4]}} onClick={()=>onSelect(id)} aria-label={labels[id]+' 밑그림 선택'} aria-pressed={selected===id}>{id==='blank'?<Sketchbook/>:<img src={artUrl(id,true)} alt="" draggable="false"/>}</button>)}
 </div><div className="picker-pages visual-pages"><button disabled={page===0} onClick={()=>setPage(page-1)} aria-label="이전 도안"><ChevronLeft size={32}/></button><div className="page-dots">{Array.from({length:pages},(_,i)=><button key={i} aria-label={`도안 ${i+1}페이지`} aria-current={page===i?'page':undefined} onClick={()=>setPage(i)}><span/></button>)}</div><button disabled={page===pages-1} onClick={()=>setPage(page+1)} aria-label="다음 도안"><ChevronRight size={32}/></button></div></>;
}
